// flow-typed signature: 1fe85b3d664c9571877dbbfce98e8e9b
// flow-typed version: <<STUB>>/ban-sensitive-files_v^1.9.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ban-sensitive-files'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ban-sensitive-files' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ban-sensitive-files/bin/ban' {
  declare module.exports: any;
}

declare module 'ban-sensitive-files/src/ban' {
  declare module.exports: any;
}

declare module 'ban-sensitive-files/src/check-npmrc-file' {
  declare module.exports: any;
}

declare module 'ban-sensitive-files/src/check-sensitive-files' {
  declare module.exports: any;
}

declare module 'ban-sensitive-files/src/collect-files' {
  declare module.exports: any;
}

declare module 'ban-sensitive-files/src/re-to-regexp' {
  declare module.exports: any;
}

declare module 'ban-sensitive-files/src/rule-to-tester' {
  declare module.exports: any;
}

declare module 'ban-sensitive-files/src/sensitive-files' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ban-sensitive-files/bin/ban.js' {
  declare module.exports: $Exports<'ban-sensitive-files/bin/ban'>;
}
declare module 'ban-sensitive-files/src/ban.js' {
  declare module.exports: $Exports<'ban-sensitive-files/src/ban'>;
}
declare module 'ban-sensitive-files/src/check-npmrc-file.js' {
  declare module.exports: $Exports<'ban-sensitive-files/src/check-npmrc-file'>;
}
declare module 'ban-sensitive-files/src/check-sensitive-files.js' {
  declare module.exports: $Exports<'ban-sensitive-files/src/check-sensitive-files'>;
}
declare module 'ban-sensitive-files/src/collect-files.js' {
  declare module.exports: $Exports<'ban-sensitive-files/src/collect-files'>;
}
declare module 'ban-sensitive-files/src/re-to-regexp.js' {
  declare module.exports: $Exports<'ban-sensitive-files/src/re-to-regexp'>;
}
declare module 'ban-sensitive-files/src/rule-to-tester.js' {
  declare module.exports: $Exports<'ban-sensitive-files/src/rule-to-tester'>;
}
declare module 'ban-sensitive-files/src/sensitive-files.js' {
  declare module.exports: $Exports<'ban-sensitive-files/src/sensitive-files'>;
}
