// flow-typed signature: 05002e8137b84f9d23c868c6f70327ec
// flow-typed version: <<STUB>>/dom4_v^1.8.5/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dom4'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dom4' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dom4/build/dom4' {
  declare module.exports: any;
}

declare module 'dom4/build/dom4.max' {
  declare module.exports: any;
}

declare module 'dom4/testrunner' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dom4/build/dom4.js' {
  declare module.exports: $Exports<'dom4/build/dom4'>;
}
declare module 'dom4/build/dom4.max.js' {
  declare module.exports: $Exports<'dom4/build/dom4.max'>;
}
declare module 'dom4/testrunner.js' {
  declare module.exports: $Exports<'dom4/testrunner'>;
}
