// flow-typed signature: 26adea1587610776810ce7fe8ff3f1a1
// flow-typed version: <<STUB>>/normalize.css_v^6.0.0/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'normalize.css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'normalize.css' {
  declare module.exports: any;
}
