// flow-typed signature: 7487eb3ab4695aaa04b2b3532b471eaa
// flow-typed version: <<STUB>>/postcss-fixes_v^2.0.1/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-fixes'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-fixes' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'postcss-fixes/index' {
  declare module.exports: $Exports<'postcss-fixes'>;
}
declare module 'postcss-fixes/index.js' {
  declare module.exports: $Exports<'postcss-fixes'>;
}
